name: Muhlogger
version: '${project.version}'
main: pw.valaria.muhlogger.Muhlogger
api-version: 1.18
load: STARTUP

commands:
  muhlogger:
    permission: muhlogger.command
    usage: /<command> [reload]